[project]
name = "discord-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "pandas>=2.2.3",
]
